# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-13 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20180413_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='desc',
            field=models.TextField(default='none'),
        ),
    ]
